# Generated by Django 3.2.2 on 2021-07-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperapp', '0002_alter_paper_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='department',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='year',
        ),
        migrations.AddField(
            model_name='paper',
            name='title',
            field=models.CharField(default='RANDOM', max_length=200),
        ),
    ]
