# Generated by Django 3.2.2 on 2021-07-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperapp', '0003_auto_20210702_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
